name: Cloud Native CI/CD Pipeline
on:
  push: 
    branches:
      - main
  workflow_dispatch: 
jobs:
  build-and-deploy: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Show Current Directory
        run: pwd 
      - name: List Repository Files
        run: ls -la 
      - name: Show Project Structure
        run: tree -L 2 
      - name: Check Docker Version
        run: docker --version 
      - name: Build Backend Docker Image
        run: docker build -t backend-app:v8 ./backend
      - name: Verify Backend Docker Image
        run: docker images 
      - name: Build Frontend Docker Image 
        run: docker build -t frontend-app:v3 ./frontend 
      - name: Verify Frontend Docker Image
        run: docker images