name: Cloud Native CI/CD Pipeline.yml
on:
  push: 
    branches:
      - main
  workflow_dispatch: 
jobs:
  checkout-repo: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Show current Directory
        run: pwd 
      - name: List repository files
        run: ls -la 
      - name: Show project structure
        run: tree -L 2 